# Generated by Django 4.0 on 2023-12-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatmodel',
            name='sourceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceId', to='users.user'),
        ),
        migrations.AddField(
            model_name='userchatmodel',
            name='targetId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetId', to='users.user'),
        ),
        migrations.AddField(
            model_name='relationships',
            name='followedUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedUserId', to='users.user'),
        ),
        migrations.AddField(
            model_name='relationships',
            name='followerUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followerUserId', to='users.user'),
        ),
    ]
